version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: America/Chicago
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: America/Chicago
    open-pull-requests-limit: 99
